from modules.pessoa import Pessoa
from modules.aluno import Aluno
from modules.funcionario import Funcionario
from modules.matematica import Matematica
from modules.portugues import Portugues

if __name__ == "__main__":

    # Instanciando e printando os objetos e atributos da classe Pessoa.
    marcos = Pessoa("Marcos Lima", "9.657.544", "Rua M", "(11) 97458-2201")
    print(marcos.get_nome())
    print(marcos.get_rg())
    print(marcos.get_endereco())
    print(marcos.get_contato())
    print("\n")

    joana = Pessoa("Joana Freixo", "5.954.662", "Rua J", "(83) 95521-3200")
    print(joana.get_nome())
    print(joana.get_rg())
    print(joana.get_endereco())
    print(joana.get_contato())
    print("\n")

    penelope = Pessoa("Penélope Chamosa", "8.555.104", "Rua P", "(87) 98821-3620")
    print(penelope.get_nome())
    print(penelope.get_rg())
    print(penelope.get_endereco())
    print(penelope.get_contato())
    print("\n")

    elza = Pessoa("Elza Frozen", "2.247.194", "Rua E", "(89) 97451-1132")
    print(elza.get_nome())
    print(elza.get_rg())
    print(elza.get_endereco())
    print(elza.get_contato())
    print("\n")

    michael = Pessoa("Michael Jackson", "9.955.412", "Rua Au!", "(81) 98651-9040")
    print(michael.get_nome())
    print(michael.get_rg())
    print(michael.get_endereco())
    print(michael.get_contato())
    print("\n")

    # Intanciando e printando os objetos da classe Aluno
    eugenio = Aluno("Eugênio Candeias", "2.321.554", "Rua E", "(87) 98541-7999", "AL001")
    print(eugenio.get_nome())
    print(eugenio.get_rg())
    print(eugenio.get_endereco())
    print(eugenio.get_contato())
    print(eugenio.get_matricula())
    print("\n")

    vinicius = Aluno("Vinicius Noia", "4.545.788", "Rua V", "(82) 99951-7092", "AL002")
    print(vinicius.get_nome())
    print(vinicius.get_rg())
    print(vinicius.get_endereco())
    print(vinicius.get_contato())
    print(vinicius.get_matricula())
    print("\n")

    clara = Aluno("Clara Marta", "2.741.280", "Rua C", "(21) 99755-7141", "AL003")
    print(clara.get_nome())
    print(clara.get_rg())
    print(clara.get_endereco())
    print(clara.get_contato())
    print(clara.get_matricula())
    print("\n")

    pedro = Aluno("Pedro Rocha", "1.001.585", "Rua P", "(21) 97755-7110", "AL004")
    print(pedro.get_nome())
    print(pedro.get_rg())
    print(pedro.get_endereco())
    print(pedro.get_contato())
    print(pedro.get_matricula())
    print("\n")

    mario = Aluno("Mario Cesar", "7.701.518", "Rua M", "(21) 99825-7982", "AL005")
    print(mario.get_nome())
    print(mario.get_rg())
    print(mario.get_endereco())
    print(mario.get_contato())
    print(mario.get_matricula())
    print("\n")

    # Intanciando e printando os objetos da classe Aluno de Matematica
    helder = Matematica("Helder Moura", "1.234.567", "Rua H", "(81) 99721-7421", "MT01", 10.0)
    print(helder.get_nome())
    print(helder.get_rg())
    print(helder.get_endereco())
    print(helder.get_contato())
    print(helder.get_matricula())
    print(helder.get_nota())
    print("\n")

    silas = Matematica("Silas Brandão", "5.844.665", "Rua S", "(83) 98521-8522", "MT02", 9.5)
    print(silas.get_nome())
    print(silas.get_rg())
    print(silas.get_endereco())
    print(silas.get_contato())
    print(silas.get_matricula())
    print(silas.get_nota())
    print("\n")
    
    lorena = Matematica("Lorena Gomes", "4.211.005", "Rua L", "(85) 99000-8418", "MT03", 8.9)
    print(lorena.get_nome())
    print(lorena.get_rg())
    print(lorena.get_endereco())
    print(lorena.get_contato())
    print(lorena.get_matricula())
    print(lorena.get_nota())
    print("\n")

    pamella = Matematica("Pamella Melo", "1.201.007", "Rua P", "(81) 99190-8518", "MT04", 10.0)
    print(pamella.get_nome())
    print(pamella.get_rg())
    print(pamella.get_endereco())
    print(pamella.get_contato())
    print(pamella.get_matricula())
    print(pamella.get_nota())
    print("\n")

    anderson = Matematica("Anderson Bartô", "7.555.047", "Rua A", "(81) 99197-9251", "MT05", 7.0)
    print(anderson.get_nome())
    print(anderson.get_rg())
    print(anderson.get_endereco())
    print(anderson.get_contato())
    print(anderson.get_matricula())
    print(anderson.get_nota())
    print("\n")

    # Intanciando e printando os objetos da classe Aluno de Portugues
    denise = Portugues("Denise Junqueira", "4.287.544", "Rua D", "(82) 98221-0051", "PT01", 9.0)
    print(denise.get_nome())
    print(denise.get_rg())
    print(denise.get_endereco())
    print(denise.get_contato())
    print(denise.get_matricula())
    print(denise.get_nota())
    print("\n")

    fernando = Portugues("Fernando Aragão", "4.587.214", "Rua F", "(81) 98778-04100", "PT02", 8.5)
    print(fernando.get_nome())
    print(fernando.get_rg())
    print(fernando.get_endereco())
    print(fernando.get_contato())
    print(fernando.get_matricula())
    print(fernando.get_nota())
    print("\n")

    denise = Portugues("Denise Junqueira", "4.287.544", "Rua D", "(82) 98221-0051", "PT03", 5.0)
    print(denise.get_nome())
    print(denise.get_rg())
    print(denise.get_endereco())
    print(denise.get_contato())
    print(denise.get_matricula())
    print(denise.get_nota())
    print("\n")

    isabel = Portugues("Isabel Barroso", "3.157.024", "Rua I", "(11) 99421-0211", "PT04", 8.45)
    print(isabel.get_nome())
    print(isabel.get_rg())
    print(isabel.get_endereco())
    print(isabel.get_contato())
    print(isabel.get_matricula())
    print(isabel.get_nota())
    print("\n")

    lilian = Portugues("Lilian Potter", "6.587.625", "Rua L", "(21) 9991-8755", "PT05", 10.0)
    print(lilian.get_nome())
    print(lilian.get_rg())
    print(lilian.get_endereco())
    print(lilian.get_contato())
    print(lilian.get_matricula())
    print(lilian.get_nota())
    print("\n")

    # Intanciando e printando os objetos da classe Funcionario
    marcone = Funcionario("Marcone Marinho", "1.221.540", "Rua M", "(81) 97821-5451", "FUN01", "Analista de Redes")
    print(marcone.get_nome())
    print(marcone.get_rg())
    print(marcone.get_endereco())
    print(marcone.get_contato())
    print(marcone.get_id_func())
    print(marcone.get_cargo())
    print("\n")

    jorge = Funcionario("Jorge Medeiros", "4.011.052", "Rua J", "(11) 97781-5001", "FUN02", "Engenheiro de Software")
    print(jorge.get_nome())
    print(jorge.get_rg())
    print(jorge.get_endereco())
    print(jorge.get_contato())
    print(jorge.get_id_func())
    print(jorge.get_cargo())
    print("\n")

    rodolfo = Funcionario("Rodolfo Portela", "2.881.984", "Rua R", "(22) 98581-5321", "FUN03", "Gerente de Negócios")
    print(rodolfo.get_nome())
    print(rodolfo.get_rg())
    print(rodolfo.get_endereco())
    print(rodolfo.get_contato())
    print(rodolfo.get_id_func())
    print(rodolfo.get_cargo())
    print("\n")

    leticia = Funcionario("Leticia Couraça", "1.061.050", "Rua F", "(88) 97477-4201", "FUN04", "Engenheiro de Dados")
    print(leticia.get_nome())
    print(leticia.get_rg())
    print(leticia.get_endereco())
    print(leticia.get_contato())
    print(leticia.get_id_func())
    print(leticia.get_cargo())
    print("\n")

    jairo = Funcionario("Jairo Rosa", "9.399.015", "Rua J", "(82) 98899-1101", "FUN05", "Operador de Elevador")
    print(jairo.get_nome())
    print(jairo.get_rg())
    print(jairo.get_endereco())
    print(jairo.get_contato())
    print(jairo.get_id_func())
    print(jairo.get_cargo())
    print("\n")

